<h3 class="text-light bg-dark">Add Product</h3>
<?php echo $this->tag->form("products/add"); ?>
    <div class="form-group">
        <label for="productname">Product Name</label>
        <!-- <input class="form-control" id='productname' type="text" placeholder="Product Name">
     -->
     <?php echo $this->tag->textField(['name' => 'productname','maxlength' => 30, 'placeholder' => 'Product Name', 'class' => 'form-control']); ?>
    </div>
    <div class="form-group">
    <label for="description">Description</label>
    <?php echo $this->tag->textArea(['name' => 'description',"rows"=>"3",'maxlength' => 30, 'placeholder' => 'Add Product Description', 'class' => 'form-control']); ?>
    <!-- <textarea class="form-control" id="description" rows="3" placeholder="Add Product Description"></textarea> -->
    </div>
    <div class="form-group">
        <label for="tag">Tag</label>
        <?php echo $this->tag->textField(['name' => 'tag','maxlength' => 30, 'placeholder' => 'Add Product Tag', 'class' => 'form-control']); ?>
        <!-- <input class="form-control" id='tag' type="text" placeholder="Add Product Tag"> -->
    </div>
    <div class="form-group">
        <label for="price">Price</label>
        <?php echo $this->tag->textField(['name' => 'price','maxlength' => 30, 'placeholder' => 'Price', 'class' => 'form-control']); ?>
        <!-- <input class="form-control" id='price' type="text" placeholder="Price"> -->
    </div>
    <div class="form-group">
        <label for="stock">Stock</label>
        <?php echo $this->tag->textField(['name' => 'stock','maxlength' => 30, 'placeholder' => 'Stock', 'class' => 'form-control']); ?>
        <!-- <input class="form-control" id='stock' type="text" placeholder="Quantity"> -->
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>