<h3 class="text-light bg-dark">Add Order</h3>
<form>
    <div class="form-group">
        <label for="customername"> Customer name</label>
        <!-- <input class="form-control" id='customername' type="text" placeholder=" Customer name"> -->
        <?php echo $this->tag->textField(['name' => 'customername','maxlength' => 30, 'placeholder' => 'Customer Name', 'class' => 'form-control']); ?>
    
    </div>
    <div class="form-group">
         <label for="customeraddress">Customer Address</label>
         <!-- <textarea class="form-control" id="customeraddress" rows="3" placeholder="Add Customer Address"></textarea> -->
         <?php echo $this->tag->textArea(['name' => 'customeraddress',"rows"=>"3",'maxlength' => 30, 'placeholder' => 'Add Customer Address', 'class' => 'form-control']); ?>
    </div>
    <div class="form-group">
        <label for="zipcode">Zipcode</label>
        <!-- <input class="form-control" id='zipcode' type="text" placeholder="Zipcode"> -->
        <?php echo $this->tag->textField(['name' => 'zipcode','maxlength' => 30, 'placeholder' => 'Zipcode', 'class' => 'form-control']); ?>
    </div>
    <div class="form-group">
        <label for="product">Product</label>
        <!-- <input class="form-control" id='product' type="text" placeholder="Select Product"> -->
        <?php 
            // $products = $this->products;
            echo $this->tag->selectField(
            'product', // name attribute of the <select> element
            $products->toArray(), // associative array with options and values
            ['class' => 'form-control', 'id' => 'product'], // additional attributes for <select> element
            );
        ?>
    </div>
    <div class="form-group">
        <label for="stock">Quantity</label>
        <input class="form-control" id='stock' type="text" placeholder="Quantity">
    </div>
    
    <button type="submit" class="btn btn-primary">Submit</button>
</div> 
</form>