<h3 class="text-light bg-dark">SETTINGS</h3>
<form>
    <div class="form-group">
        <label for="titleoptimization"> Title optimization </label>
        <input class="form-control" id='titleoptimization' type="text" placeholder="Title optimization">
    </div>
    <div class="form-group">
    <label for="defaultprice">Default Price</label>
    <textarea class="form-control" id="defaultprice" rows="3" placeholder="Default Price"></textarea>
    </div>
    <div class="form-group">
        <label for="defaultzipcode">Default Zipcode</label>
        <input class="form-control" id='defaultzipcode' type="text" placeholder="Default Zipcode">
    </div>
    <div class="form-group">
        <label for="defaultstock">Default Stock</label>
        <input class="form-control" id='defaultstock' type="text" placeholder="Default Stock">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</div> 
</form>